export const ARCHIVE_TYPES = ['Borehole','Coral','Documents','FluvialSediment','GlacierIce','GroundIce','LakeSediment','MarineSediment','Midden','MolluskShell','Other','Peat','Sclerosponge','Shoreline','Speleothem','TerrestrialSediment','Wood']

export const INTERP_VARIABLES = ['C3C4Ratio','circulationIndex','circulationVariable','cloudiness','dissolvedOxygen','dust','ELA','effectivePrecipitation','evaporation','fire','groundWaterIsotope','growingDegreeDays','hydrologicBalance','lakeWaterIsotope','meltwater','precipitation','precipitationDeuteriumExcess','precipitationIsotope','productivity','relativeHumidity','relativeSeaLevel','salinity','seaIce','seasonality','seawaterIsotope','streamflow','sunlight','surfacePressure','temperature','upwelling','windSpeed']

export const SEASONALITY = ['Annual','Spring','Summer','Fall','Winter','Coldest Month','Warmest Month','Growing Season','Wet Season','Spr-Sum','Win-Spr','subannual','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Jan-Mar','Jan-Jun','Jan-Sep','Feb-Apr','Mar-May','Apr-Jun','Apr-Sep','Jun-Aug','Jun-Sep','Jul-Sep','Aug-Oct','Sep-Nov','Oct-Dec','Nov-Jan','Dec-Feb','Dec-Mar']

export const PROXY_TYPES = ['10Be','accumulation rate','ACL','Al/Ca','alkenone','n-alkane','amoeba','Ba/Ca','biomarker','BIT','BSi','bulk density','bulk sediment','C/N','CaCO3','calcite','carbonate','CBT','cellulose','charcoal','chironomid','chrysophyte assemblage','cladoceran','coccolithophore','d13C','d15N','d18O','dD','diatom','dinocyst','dry bulk density','Fe','Fe/Ca','foraminifera','GDGT','grain size','HBI','historical','humification','IP25','lake level','LDI','macrofossils','magnetic','magnetic susceptibility','Mg/Ca','multiproxy','ostracod','pH','pollen','radiolaria','Rb','reflectance','ring width','Sr/Ca','TEX86','Ti','Ti/Ca','TOC','total nitrogen','varve thickness']

export const PROXY_GENERAL = ['biogenic','biomarker','borehole','cryophysical','dendrophysical','elemental','faunal assemblage','floral assemblage','historical','isotopic','mineral','multiproxy','pyrogenic','reflectance','sedimentology','stratigraphy']

export const UNITS = ['cm','cm/kyr','cm/yr','count','count/cm2','count/cm2/yr','count/g','count/yr','degC','fraction','g/cm3','g/L','grayscale','kg/m3','m','mg/L','mm','mm/yr','mmol/mol','percent','permil','pH','ppb','ppm','ratio','ug/g','ug/L','umol/mol','unitless','year','yr 14C BP','yr AD','yr b2k','yr BP','yr ka','z score']

export const VARIABLE_NAMES = ['age','age14C','year','d13C','d15N','d18O','d2H','dD','deuteriumExcess','accumulation','BSi','bulkDensity','CaCO3','calcite','carbonate','charcoal','chlorin','depth','depthBottom','depthTop','diatom','dinocyst','grainSize','grayscale','humidificationIndex','LOI','MAR','Mg/Ca','MS','MXD','nitrogen','peat','pH','pollen','precipitation','reflectance','ringWidth','salinity','sedimentationRate','Sr/Ca','sulfur','TEX86','Ti','Ti/Ca','TOC','totalNitrogen','totalPhosphorus','varveThickness','temperature']
